### ISSUE TITLE
How to include maxage parameter in logrotate file ?

### ISSUE THREAD

**Issue by GuptaArpit07** [sous-chefs/logrotate#126]
Hi,
I have the logrotate cookbook which I have used in my deploy recipe to include the logrotation of log files.
Below is the blog from my file for creating the logrotate file for app logs.
`logrotate_app 'app' do
  path ["#{node['deploy']['logdir']}/#{node['deploy']['nodejs']['application_name']}/app*log"]
  size '5M'
  frequency 'daily'
  rotate 5
  options ['missingok', 'delaycompress', 'notifempty', 'sharedscripts', 'copytruncate']
  create "664 #{node['deploy']['user']} root"
end`

Can you please help me in including the maxage parameter with correct syntax as I am unable to do so?
I tried adding as : -
maxage 60
maxage=>60
But the file is not getting updated after running the chef-client on the server due to some syntax mismatch.

Thanks

**Comment by stevendanna** [comment]
Hi,

```
maxage 60
```

or 

```
maxage "60"
```

should work.  Can you share the error message you are getting when trying to use that option?

**Comment by GuptaArpit07** [comment]
There is no such error I am getting. But when I include the above value in the cookbook and upload it.
I run chef-client to apply the changes but the logrotate file present on the server is not getting updated with the maxage value.

**Comment by stevendanna** [comment]
If you can provide debug output from the chef-client run that would be helpful.  Otherwise, I can try to reproduce it locally but not until this weekend most likely.
