### ISSUE TITLE
merge into chef core

### ISSUE THREAD

**Issue by jlosito** [sous-chefs/logrotate#131]
I find myself using the logrotate_app resource in half of my cookbooks in order to maintain logs. Is there any plans on merging it into the core functionality of chef?

**Comment by stevendanna** [comment]
@jlosito Thanks!  I definitely agree and I think @tas50 agrees as well.  At the very least, I think it should move back to being a Chef-maintained cookbook. I don't use this cookbook much anymore and would be very happy to move it back to Chef however it is likely going to be a while until I can work on it again.

**Comment by tas50** [comment]
@stevendanna if you want to move this back to chef-cookbooks we can start the process of moving it into core

**Comment by tas50** [comment]
This entirely slipped my mind, but I'll see what I can do to get this into Chef Infra Client 15.4

**Comment by jblaine** [comment]
AFAICT, this did not make it into 15.4+ or 16.x, right?

**Comment by tas50** [comment]
It did not make the cut.
