### ISSUE TITLE
path property required even when the action is :disable

### ISSUE THREAD

**Issue by kpmueller** [sous-chefs/logrotate#148]
```    Chef::Exceptions::ValidationFailed
    ----------------------------------
    path is a required property

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/piazza_app/recipes/logs.rb

     32: logrotate_app 'petty_gc' do
     33:   action :disable
     34: end
     35:
```

I have a resource declaration to remove an old log rotation. It does not have a path, since it only needs to remove a chef log rotation by Chef name (I assume?). I don't know if this is something you want to fix or not, but I thought i would flag it.

It may be an artifact of Chef 16+ where required properties are actually required, now :)

**Comment by bmhughes** [comment]
PR coming shortly that fixes this.

**Comment by kpmueller** [comment]
thanks much!
