### ISSUE TITLE
Should ensure that /etc/cron.hourly/logrotate exists

### ISSUE THREAD

**Issue by nicwaller** [sous-chefs/logrotate#77]
This cookbook allows the specification of `hourly` as an option, but it does not guarantee that an hourly cron entry exists.

```
$ ls -l /etc/cron.{hourly,daily}/logrotate
ls: cannot access /etc/cron.hourly/logrotate: No such file or directory
-rwxr-xr-x 1 root root 372 Jan 22  2014 /etc/cron.daily/logrotate
```

This issue is [commonly](http://stackoverflow.com/a/25485313) asked about. The logrotate man page provides this guidance.

> Log files are rotated every hour. Note that usually logrotate is configured to be run by cron daily. You have to change this configuration and run logrotate hourly to be able to really rotate logs hourly.

In my opinion, this cookbook should create `/etc/cron.hourly/logrotate` if the hourly option is used for any definitions of `logrotate_app`.

**Comment by gawbul** [comment]
:+1:

**Comment by yoshiwaan** [comment]
It would be an excellent addition to this cookbook if the system ensured there was a /etc/cron.<time> file that matches the shorted time used by the cookbook resources.
